export const btnStyle = {
  fontSize: '18px',
  textDecoration: 'none',
  lineHeight: 1,
  borderRadius: '500px',
  padding: '18px 48px 16px',
  transitionProperty: 'background-color,border-color,color,box-shadow,filter',
  transitionDuration: '.3s',
  borderWidth: 0,
  letterSpacing: '2px',
  width: '200px',
  textTransform: 'uppercase',
  whiteSpace: 'normal',
  display: 'block',
  marginBottom: 0,
  fontWeight: 700,
  verticalAlign: 'middle',
  cursor: 'pointer',
  border: '1px solid transparent',
  textAlign: 'center',
  marginLeft: 'auto',
  marginRight: 'auto',
  outline: 'none',
};
